# Docker Compose Local Development Setup
#
# This starts a local multi-container development environment
# with Postgres, Redis, Celery, and Django.
# The configuration comes from .envs/local
#
# To run:
#   $ make dockerbuild
#   $ make dockerserve

version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_metabase_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker-compose/django/Dockerfile
    image: ethicaladserver_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/local/django
      - ./.envs/local/postgres
    ports:
      - "${ETHICALADS_DJANGO_PORT:-5000}:5000"
    command: /start
    # Allow us to run `docker attach` and get
    # control on STDIN and be able to debug our code with interactive pdb
    stdin_open: true
    tty: true

  postgres:
    build:
      context: .
      dockerfile: ./docker-compose/postgres/Dockerfile
    image: ethicaladserver_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/local/postgres

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: ethicaladserver_local_celeryworker
    depends_on:
      - redis
      - postgres

    env_file:
      - ./.envs/local/django
      - ./.envs/local/postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ethicaladserver_local_celerybeat
    depends_on:
      - redis
      - postgres

    env_file:
      - ./.envs/local/postgres
      - ./.envs/local/django

    ports: []
    command: /start-celerybeat

  frontend:
    build:
      context: .
      dockerfile: ./docker-compose/frontend/Dockerfile
    ports: []
    volumes:
      - .:/app

#  metabase:
#    image: metabase/metabase
#    ports:
#      - ${ETHICALADS_METABASE_PORT:-3000}:3000
#    volumes:
#      - local_metabase_data:/metabase-data
